name: Code Analysis

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  code-validation:
    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4, 8.5]
        symfony: [6.5, 7.4, 8.0]
        actions:
          - name: Composer validate
            run: composer validate --ansi --strict

          - name: Static analysis
            run: composer phpstan

          - name: Style check
            run: composer check-cs

          - name: Unit tests
            run: composer coverage
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        shell: bash
        run:
          if [ "${{ matrix.symfony }}" != "" ]; then composer require "symfony/filesystem:${{ matrix.symfony }}" --no-update --no-interaction --prefer-dist --optimize-autoloader; fi;
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - run: ${{ matrix.actions.run }}

      - name: Coverage diff
        uses: OpenClassrooms/coverage-checker@v1.7.0
        if: ${{ hashFiles('build/coverage/coverage.xml') != '' && github.event_name == 'pull_request' }}
        with:
          action: check
          files: '[{"coverage": "build/coverage/coverage.xml", "summary": "coverage-summary.json", "label": "Coverage", "badge": "coverage.svg"}]'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Coverage update
        uses: OpenClassrooms/coverage-checker@v1.7.0
        if: ${{ hashFiles('build/coverage/coverage.xml') != '' && github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          action: update
          files: '[{"coverage": "build/coverage/coverage.xml", "summary": "coverage-summary.json", "label": "Coverage", "badge": "coverage.svg"}]'
          token: ${{ secrets.GITHUB_TOKEN }}
